image: openmole/build

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
build:
  stage: build
  script:
    - cd openmole
    - '(cd build-system && sbt clean publishLocal)'
    - '(cd libraries && sbt clean publishLocal)'
    - '(cd openmole && sbt clean publishLocal)'
    - cd ..
    - ./gradlew assemble

