image: gradle:alpine

variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
build:
  stage: build
  script:
    - ./gradlew assemble
